-- Cleanup existing policies that might conflict
-- This allows us to reapply migrations cleanly

-- Drop existing policies if they exist
drop policy if exists "Users can read own data" on public.users;
drop policy if exists "Users can update own data" on public.users;
drop policy if exists "Admins can read all users" on public.users;
drop policy if exists "Anyone can read categories" on public.categories;
drop policy if exists "Admins can manage categories" on public.categories;
drop policy if exists "Anyone can read available products" on public.products;
drop policy if exists "Admins can manage products" on public.products;
drop policy if exists "Anyone can read combos" on public.combos;
drop policy if exists "Admins can manage combos" on public.combos;
drop policy if exists "Users can manage own cart" on public.cart_items;
drop policy if exists "Users can read own orders" on public.orders;
drop policy if exists "Users can create orders" on public.orders;
drop policy if exists "Users can update own orders" on public.orders;
drop policy if exists "Admins can manage all orders" on public.orders;
drop policy if exists "Anyone can read delivery persons" on public.delivery_persons;
drop policy if exists "Admins can manage delivery persons" on public.delivery_persons;
drop policy if exists "Users can read own notifications" on public.notifications;
drop policy if exists "Anyone can create notifications" on public.notifications;
drop policy if exists "Users can update own notifications" on public.notifications;
drop policy if exists "Users can read own loyalty" on public.loyalty_transactions;
drop policy if exists "Anyone can create loyalty transactions" on public.loyalty_transactions;
drop policy if exists "Anyone can read active campaigns" on public.campaigns;
drop policy if exists "Admins can manage campaigns" on public.campaigns;
drop policy if exists "Users can read own usage" on public.campaign_usage;
drop policy if exists "Anyone can create usage" on public.campaign_usage;
drop policy if exists "Users can read own subscriptions" on public.subscriptions;
drop policy if exists "Anyone can create subscriptions" on public.subscriptions;
drop policy if exists "Admins can manage subscriptions" on public.subscriptions;
drop policy if exists "Users can read own refunds" on public.refunds;
drop policy if exists "Users can create refunds" on public.refunds;
drop policy if exists "Admins can manage refunds" on public.refunds;
drop policy if exists "Anyone can read roles" on public.roles;
drop policy if exists "Admins can manage roles" on public.roles;
drop policy if exists "Anyone can read banners" on public.banners;
drop policy if exists "Admins can manage banners" on public.banners;
drop policy if exists "Anyone can read approved reviews" on public.reviews;
drop policy if exists "Users can create reviews" on public.reviews;
drop policy if exists "Admins can manage reviews" on public.reviews;
drop policy if exists "Anyone can read settings" on public.settings;
drop policy if exists "Admins can manage settings" on public.settings;
drop policy if exists "Users can read own referrals" on public.referrals;
drop policy if exists "Anyone can create referrals" on public.referrals;
drop policy if exists "Anyone can update referrals" on public.referrals;
drop policy if exists "Anyone can read wallet transactions" on public.wallet_transactions;
drop policy if exists "Anyone can create wallet transactions" on public.wallet_transactions;
drop policy if exists "Users can read own messages" on public.chat_messages;
drop policy if exists "Users can send messages" on public.chat_messages;
drop policy if exists "Users can update own messages" on public.chat_messages;
drop policy if exists "Anyone can read published articles" on public.knowledge_articles;
drop policy if exists "Admins can manage articles" on public.knowledge_articles;
drop policy if exists "Users can read own gamification" on public.gamification;
drop policy if exists "Anyone can manage gamification" on public.gamification;
drop policy if exists "Users can manage own onboarding" on public.onboarding_progress;
drop policy if exists "Admins can read activity log" on public.admin_activity_log;
drop policy if exists "Anyone can create activity log" on public.admin_activity_log;
drop policy if exists "Anyone can read shifts" on public.shifts;
drop policy if exists "Admins can manage shifts" on public.shifts;
drop policy if exists "Users can manage own wishlist" on public.wishlists;
drop policy if exists "Anyone can read withdrawal requests" on public.withdrawal_requests;
drop policy if exists "Anyone can create withdrawal requests" on public.withdrawal_requests;
drop policy if exists "Admins can manage withdrawal requests" on public.withdrawal_requests;
drop policy if exists "Anyone can update withdrawal requests" on public.withdrawal_requests;
drop policy if exists "Anyone can read hostels" on public.hostels;
drop policy if exists "Admins can manage hostels" on public.hostels;
drop policy if exists "Anyone can read delivery queries" on public.delivery_queries;
drop policy if exists "Anyone can create delivery queries" on public.delivery_queries;
drop policy if exists "Admins can manage delivery queries" on public.delivery_queries;
drop policy if exists "Anyone can update delivery queries" on public.delivery_queries;
